name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Run build.cake
        run: dotnet cake build.cake
        env:
          GITHUB_ACTIONS: true

      - name: Publish Nuget Packages
        uses: actions/upload-artifact@v4
        with:
          name: Nuget Packages
          path: |
            BuildOutput/NugetPackages/**/*.nupkg
          if-no-files-found: error

      - name: Push Nuget to GitHub packages
        run: dotnet nuget push BuildOutput/NugetPackages/**/*.nupkg --source https://nuget.pkg.github.com/$GITHUB_REPOSITORY_OWNER/index.json --api-key ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
